.TH MYSTRLEN 3 "September 2025" "v0.4.1" "MyUtils Library"
.SH NAME
mystrlen \- calculate length of a string
.SH SYNOPSIS
.B #include <mystrfunctions.h>
.PP
.BI "int mystrlen(const char *" s );
.SH DESCRIPTION
The
.B mystrlen()
function calculates the length of the string pointed to by
.IR s ,
excluding the terminating null byte (\\\\0).
.SH RETURN VALUE
The number of bytes in the string pointed to by
.IR s .
.SH AUTHOR
Usairum Khan <bsdsf23a019@pucit.edu.pk>
